<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2011, The University of Alabama.

    Licensed under the Educational Community License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy of the License at
    http://www.osedu.org/licenses/ECL-2.0

    Unless required by applicable law or agreed to in writing, software distributed
    under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
    OF ANY KIND, either express or implied. See the License for the specific language governing
    permissions and limitations under the License.
-->
<xsl:stylesheet
        version="1.0"
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:mods="http://www.loc.gov/mods/v3"
        xmlns:etd="http://www.ndltd.org/standards/metadata/etdms/1.0/"
        xmlns:facet="http://libcontent.lib.ua.edu/digital/schemas/facets.xsd">

    <xsl:output
            method="xml"
            encoding="utf-8"
            indent="no"
            />
    <xsl:strip-space elements="*"/>

    <xsl:template match="*|node()">
        <xsl:value-of select="text()"/>
        <xsl:text>&#32;</xsl:text>
        <xsl:apply-templates/>
    </xsl:template>

    <xsl:template match="/">
        <add>
            <doc>
                <xsl:for-each select=".//mods:mods/mods:titleInfo">
                    <field name="title">
                        <xsl:value-of select="mods:nonSort/text()" />
                        <xsl:value-of select="mods:title/text()" /><xsl:if test="mods:subTitle/text()">: <xsl:value-of select="mods:subTitle/text()"/></xsl:if>
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:mods/mods:name">
                    <field name="creator">
                        <xsl:value-of select="mods:namePart/text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:note[@displayLabel='Description']">
                    <field name="description">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:abstract">
                    <field name="abstract">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:genre">
                    <field name="genre">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <!-- Research Only -->
                <xsl:if test="substring(.//mods:identifier[@name='local'],2,4) = '0015'">
                    <xsl:for-each select=".//mods:extension/etd:discipline">
                        <field name="discipline">
                            <xsl:value-of select="text()" />
                        </field>
                    </xsl:for-each>
                </xsl:if>

                <xsl:for-each select=".//mods:mods/mods:identifier[@type='uri']">
                    <field name="_purl">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <!-- Preliminary Metadata -->
                <xsl:for-each select=".//mods:recordInfo/mods:recordOrigin">
                    <xsl:if test="text()='Preliminary metadata generated by script'">
                        <field name="_oai_no_export">Preliminary</field>
                    </xsl:if>
                </xsl:for-each>

                <!-- ASERL and similarly set up virtual collections -->
                <xsl:for-each select=".//mods:relatedItem[@displayLabel='Virtual Collection']/mods:location/mods:url">
                    <field name="_virtual_collection">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:subject">
                    <field name="subject">
                        <xsl:apply-templates />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:*[@keyDate='yes']">
                    <field name="display_date">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:dateIssued">
                    <field name="date">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:dateCreated">
                    <field name="date">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:extension/facet:date_f">
                    <xsl:variable name="point">
                        <xsl:choose>
                            <xsl:when test="@point">_<xsl:value-of select="@point"></xsl:value-of></xsl:when>
                            <xsl:otherwise></xsl:otherwise>
                        </xsl:choose>
                    </xsl:variable>

                    <field name="date{$point}_tsf">
                        <xsl:value-of select="text()" />
                    </field>

                    <xsl:if test="@circa">
                        <field name="date{$point}_circa">
                            <xsl:value-of select="@circa" />
                        </field>
                    </xsl:if>

                    <xsl:if test="@no">
                        <field name="date{$point}_no">
                            <xsl:value-of select="@no" />
                        </field>
                    </xsl:if>
                </xsl:for-each>

                <xsl:for-each select=".//mods:typeOfResource">
                    <field name="type">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <xsl:for-each select=".//mods:location/mods:physicalLocation">
                    <xsl:choose>
                        <xsl:when test="@type='collection'">
                            <field name="collection">
                                <xsl:value-of select="text()" />
                            </field>
                        </xsl:when>
                        <xsl:when test="@type='collectionNumber'">
                            <field name="collection_number">
                                <xsl:value-of select="text()" />
                            </field>
                        </xsl:when>
                        <xsl:when test="@type='boxNumber'">
                            <field name="box_number">
                                <xsl:value-of select="text()" />
                            </field>
                        </xsl:when>
                        <xsl:when test="@type='folderNumber'">
                            <field name="folder_number">
                                <xsl:value-of select="text()" />
                            </field>
                        </xsl:when>
                        <xsl:otherwise>
                            <field name="location">
                                <xsl:value-of select="text()" />
                            </field>
                        </xsl:otherwise>
                    </xsl:choose>
                </xsl:for-each>

                <xsl:for-each select=".//mods:physicalDescription">
                    <field name="physdesc">
                        <xsl:value-of select="text()" />
                    </field>
                </xsl:for-each>

                <content>
                    <xsl:apply-templates/>
                </content>

            </doc>
        </add>
    </xsl:template>
</xsl:stylesheet>